[[redirects]]
  from = "/post"
  to = "https://blogsbe-de5369cd7cdb.herokuapp.com/post"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
